--DATA DEFINATION LANGUAGE (DDL) STATEMENTS
--CREATE
CREATE TABLE persons(
ID INT NOT NULL,
person_name VARCHAR(50) NOT NULL,
birth_date DATE,
phone_number VARCHAR(15) NOT NULL,
CONSTRAINT pk_persons PRIMARY KEY(ID)
)
--ALTER
--ADDING NEW COLUMN NAME EMAIL
ALTER TABLE persons
ADD email VARCHAR(50) NOT NULL 
ALTER TABLE persons
DROP COLUMN phone_number 

SELECT * 
FROM persons

--DROP TABLE persons
