-- MULTI TABLE JOIN
--USING salesDB, RETRIEVE A LIST OF ALL ORDERS, ALONG WITH THE RELATED CUSTOMER, PRODUCT AND EMPLOYEE DETAILS
--SHow Order ID , CUSTOMER NAME, SALES, PRODUCT NAME, SALES PERSON NAME,PRICE
SELECT *
FROM SALES.Orders O

SELECT *
FROM Sales.Customers

SELECT *
FROM Sales.Products
SELECT *
FROM Sales.Employees

SELECT 
  O.OrderID,
  C.FirstName+' '+C.LastName as CustomerName,
  O.Sales,
  P.Product,
  P.Price,
  E.FirstName+' '+E.LastName as SalesPersonName
 FROM Sales.Orders O
 LEFT JOIN Sales.Customers C ON O.CustomerID = C.CustomerID
 LEFT JOIN Sales.Products P ON O.ProductID = P.ProductID
 LEFT JOIN Sales.Employees E ON O.SalesPersonID = E.EmployeeID


 /*SET OPERATORS:to join rows
 RULE 1:SET OPERATORS CAN BE USED IN ALMOST ALL CLAUSES  (WHERE, GROUP BY, HAVING)
 ORDER BY IS ALLOWED ONLY ONCE AT THE END OF QUERY
 RULE 2:NUMBER OF COLUMNS MUST BE THE SAME IN ALL QUERIES
 RULE 3: DATA TYPE OF EACH COLUMN MUST BE COMPATIBLE IN ALL QUERIES
 RULE 4 :ORDER OF COLUMNS MUST BE THE SAME IN ALL QUERIES
 RULE 5:THE COLUMN NAMES IN THE RESULT SET ARE DETERMINED BY THE FIRST QUERY THUS ALIASES SHOULD BE GIVEN IN 1ST QUERY 


 UNION: RETURNS DISTINCT ROWS FROM BOTH QUERIES AND REMOVES DUPLICATE ROWS FROM RESULT
 TASK:COMBINE DATA FROM EMPLOYEES AND CUSTOMERS INTO ONE TABLE*/

 SELECT * 
 FROM Sales.Employees

 SELECT * 
 FROM Sales.Customers


 SELECT 
 --  EmployeeID,
   FirstName,
   LastName
 FROM Sales.Employees
 UNION 
 SELECT 
  -- CustomerID,
   FirstName,
   LastName
 FROM Sales.Customers

 -- UNION ALL: RETURNS ALL ROWS FROM BOTH QUERIES INCLUDING DUPLICATES
 --performance of UNION ALL is better than UNION as it does not remove duplicates
  SELECT 
   FirstName,
   LastName
 FROM Sales.Employees
 UNION  ALL
 SELECT 
   FirstName,
   LastName
 FROM Sales.Customers

 --EXCEPT:DISPLAYS DISTINCT ROWS FROM THE FIRST QUERY THAT ARE NOT IN THE SECOND QUERY
 --ONLY ONE IN WHICH WE HAVE TO TAKE CARE OF ORDER OF QUERIES AS IT AFFECTS THE RESULT
 -- FIND THE EMPLOYEES WHO ARE NOT CUSTOMERS AT THE SAME TIME
  SELECT 
   FirstName,
   LastName
 FROM Sales.Employees
 EXCEPT
 SELECT 
   FirstName,
   LastName
 FROM Sales.Customers

 --TASK :FIND THE CUSTOMERS WHO ARE NOT EMPLOYEES AT THE SAME TIME
 SELECT 
   FirstName,
   LastName
 FROM Sales.Customers
 EXCEPT
 SELECT 
   FirstName,
   LastName
 FROM Sales.Employees

 --INTERSECT:DISPLAYS DISTINCT ROWS THAT ARE COMMON IN BOTH QUERIES
 --FIND THE EMPLOYEES WHO ARE ALSO CUSTOMERS
 SELECT 
   FirstName,
   LastName
 FROM Sales.Customers
 INTERSECT
 SELECT 
   FirstName,
   LastName
 FROM Sales.Employees